// AUTO-GENERATED from rcurses/lib/rcurses/emoji.rb. Do not edit by hand.
// 8 categories, 576 emoji.

pub struct EmojiCat {
    pub name: &'static str,
    pub items: &'static [(&'static str, &'static str)],  // (glyph, label)
}

static SMILEYS: &[(&str, &str)] = &[
    ("😀", "grin"),
    ("😃", "smiley"),
    ("😄", "smile"),
    ("😁", "beaming"),
    ("😆", "laughing"),
    ("😅", "sweat smile"),
    ("🤣", "rofl"),
    ("😂", "joy"),
    ("🙂", "slight smile"),
    ("😉", "wink"),
    ("😊", "blush"),
    ("😇", "innocent"),
    ("🥰", "love face"),
    ("😍", "heart eyes"),
    ("🤩", "starstruck"),
    ("😘", "kiss"),
    ("😗", "kissing"),
    ("😚", "kiss closed"),
    ("😙", "kiss smile"),
    ("🥲", "happy tear"),
    ("😋", "yum"),
    ("😛", "tongue"),
    ("😜", "tongue wink"),
    ("🤪", "zany"),
    ("😝", "tongue closed"),
    ("🤑", "money"),
    ("🤗", "hug"),
    ("🤭", "hand mouth"),
    ("🤫", "shush"),
    ("🤔", "thinking"),
    ("🫡", "salute"),
    ("🤐", "zipper"),
    ("🤨", "raised brow"),
    ("😐", "neutral"),
    ("😑", "expressionless"),
    ("😶", "no mouth"),
    ("🫥", "dotted face"),
    ("😏", "smirk"),
    ("😒", "unamused"),
    ("🙄", "roll eyes"),
    ("😬", "grimace"),
    ("😮‍💨", "exhale"),
    ("🤥", "liar"),
    ("😌", "relieved"),
    ("😔", "pensive"),
    ("😪", "sleepy"),
    ("🤤", "drool"),
    ("😴", "sleep"),
    ("😷", "mask"),
    ("🤒", "sick"),
    ("🤕", "bandage"),
    ("🤢", "nausea"),
    ("🤮", "vomit"),
    ("🥵", "hot"),
    ("🥶", "cold"),
    ("🥴", "woozy"),
    ("😵", "dizzy"),
    ("🤯", "exploding"),
    ("🤠", "cowboy"),
    ("🥳", "party"),
    ("🥸", "disguise"),
    ("😎", "cool"),
    ("🤓", "nerd"),
    ("🧐", "monocle"),
    ("😕", "confused"),
    ("🫤", "diagonal mouth"),
    ("😟", "worried"),
    ("🙁", "frown"),
    ("😮", "open mouth"),
    ("😯", "hushed"),
    ("😲", "astonished"),
    ("😳", "flushed"),
    ("🥺", "pleading"),
    ("🥹", "holding tears"),
    ("😦", "frowning"),
    ("😧", "anguished"),
    ("😨", "fearful"),
    ("😰", "anxious"),
    ("😥", "sad relief"),
    ("😢", "cry"),
    ("😭", "sob"),
    ("😱", "scream"),
    ("😖", "confounded"),
    ("😣", "persevere"),
    ("😞", "disappointed"),
    ("😓", "downcast"),
    ("😩", "weary"),
    ("😫", "tired"),
    ("🥱", "yawn"),
    ("😤", "triumph"),
    ("😡", "rage"),
    ("😠", "angry"),
    ("🤬", "swearing"),
    ("😈", "devil smile"),
    ("👿", "devil"),
    ("💀", "skull"),
    ("☠️", "crossbones"),
    ("💩", "poop"),
    ("🤡", "clown"),
    ("👹", "ogre"),
    ("👻", "ghost"),
    ("👽", "alien"),
    ("🤖", "robot"),
    ("💋", "kiss mark"),
    ("❤️", "heart"),
    ("🧡", "orange heart"),
    ("💛", "yellow heart"),
    ("💚", "green heart"),
    ("💙", "blue heart"),
    ("💜", "purple heart"),
    ("🖤", "black heart"),
    ("🤍", "white heart"),
    ("🤎", "brown heart"),
    ("💔", "broken heart"),
    ("❤️‍🔥", "fire heart"),
    ("💕", "two hearts"),
    ("💞", "revolving hearts"),
    ("💓", "heartbeat"),
    ("💗", "growing heart"),
    ("💖", "sparkling heart"),
    ("💘", "cupid"),
    ("💝", "ribbon heart"),
    ("💟", "heart decoration"),
    ("🫶", "heart hands"),
];

static PEOPLE: &[(&str, &str)] = &[
    ("👋", "wave"),
    ("🤚", "raised back"),
    ("🖐️", "splayed hand"),
    ("✋", "raised hand"),
    ("🖖", "vulcan"),
    ("🫱", "right hand"),
    ("🫲", "left hand"),
    ("🫳", "palm down"),
    ("🫴", "palm up"),
    ("👌", "ok"),
    ("🤌", "pinched"),
    ("🤏", "pinch"),
    ("✌️", "peace"),
    ("🤞", "crossed fingers"),
    ("🫰", "index thumb"),
    ("🤟", "love you"),
    ("🤘", "rock"),
    ("🤙", "call me"),
    ("👈", "left point"),
    ("👉", "right point"),
    ("👆", "up point"),
    ("🖕", "middle finger"),
    ("👇", "down point"),
    ("☝️", "index up"),
    ("🫵", "point at viewer"),
    ("👍", "thumbsup"),
    ("👎", "thumbsdown"),
    ("✊", "fist"),
    ("👊", "punch"),
    ("🤛", "left fist"),
    ("🤜", "right fist"),
    ("👏", "clap"),
    ("🙌", "raised hands"),
    ("🫶", "heart hands"),
    ("👐", "open hands"),
    ("🤲", "palms up"),
    ("🤝", "handshake"),
    ("🙏", "pray"),
    ("✍️", "writing"),
    ("💪", "muscle"),
    ("🦾", "mechanical arm"),
    ("🧠", "brain"),
    ("👀", "eyes"),
    ("👁️", "eye"),
    ("👅", "tongue"),
    ("👄", "lips"),
    ("🫦", "biting lip"),
    ("👶", "baby"),
    ("🧒", "child"),
    ("👦", "boy"),
    ("👧", "girl"),
    ("🧑", "person"),
    ("👱", "blond"),
    ("👨", "man"),
    ("🧔", "beard"),
    ("👩", "woman"),
    ("🧓", "older person"),
    ("👴", "old man"),
    ("👵", "old woman"),
];

static ANIMALS: &[(&str, &str)] = &[
    ("🐶", "dog"),
    ("🐱", "cat"),
    ("🐭", "mouse"),
    ("🐹", "hamster"),
    ("🐰", "rabbit"),
    ("🦊", "fox"),
    ("🐻", "bear"),
    ("🐼", "panda"),
    ("🐻‍❄️", "polar bear"),
    ("🐨", "koala"),
    ("🐯", "tiger"),
    ("🦁", "lion"),
    ("🐮", "cow"),
    ("🐷", "pig"),
    ("🐸", "frog"),
    ("🐵", "monkey"),
    ("🐔", "chicken"),
    ("🐧", "penguin"),
    ("🐦", "bird"),
    ("🐤", "chick"),
    ("🦆", "duck"),
    ("🦅", "eagle"),
    ("🦉", "owl"),
    ("🦇", "bat"),
    ("🐺", "wolf"),
    ("🐗", "boar"),
    ("🐴", "horse"),
    ("🦄", "unicorn"),
    ("🐝", "bee"),
    ("🐛", "bug"),
    ("🦋", "butterfly"),
    ("🐌", "snail"),
    ("🐞", "ladybug"),
    ("🐜", "ant"),
    ("🪲", "beetle"),
    ("🐢", "turtle"),
    ("🐍", "snake"),
    ("🦎", "lizard"),
    ("🦂", "scorpion"),
    ("🐙", "octopus"),
    ("🦑", "squid"),
    ("🐠", "fish"),
    ("🐟", "tropical fish"),
    ("🐡", "blowfish"),
    ("🐬", "dolphin"),
    ("🐳", "whale"),
    ("🐋", "humpback"),
    ("🦈", "shark"),
    ("🐊", "crocodile"),
    ("🐅", "tiger2"),
    ("🐆", "leopard"),
    ("🦓", "zebra"),
    ("🦍", "gorilla"),
    ("🦧", "orangutan"),
    ("🐘", "elephant"),
    ("🦛", "hippo"),
    ("🦏", "rhino"),
    ("🐪", "camel"),
    ("🐫", "two hump camel"),
    ("🦒", "giraffe"),
    ("🦘", "kangaroo"),
    ("🦬", "bison"),
    ("🐃", "water buffalo"),
    ("🐂", "ox"),
    ("🐄", "dairy cow"),
];

static FOOD: &[(&str, &str)] = &[
    ("🍎", "apple"),
    ("🍐", "pear"),
    ("🍊", "orange"),
    ("🍋", "lemon"),
    ("🍌", "banana"),
    ("🍉", "watermelon"),
    ("🍇", "grapes"),
    ("🍓", "strawberry"),
    ("🫐", "blueberry"),
    ("🍈", "melon"),
    ("🍒", "cherry"),
    ("🍑", "peach"),
    ("🥭", "mango"),
    ("🍍", "pineapple"),
    ("🥥", "coconut"),
    ("🥝", "kiwi"),
    ("🍅", "tomato"),
    ("🥑", "avocado"),
    ("🌽", "corn"),
    ("🌶️", "pepper"),
    ("🥒", "cucumber"),
    ("🥕", "carrot"),
    ("🧄", "garlic"),
    ("🧅", "onion"),
    ("🥔", "potato"),
    ("🍞", "bread"),
    ("🥐", "croissant"),
    ("🥖", "baguette"),
    ("🧀", "cheese"),
    ("🥚", "egg"),
    ("🍳", "cooking"),
    ("🥞", "pancakes"),
    ("🧇", "waffle"),
    ("🥓", "bacon"),
    ("🍔", "burger"),
    ("🍟", "fries"),
    ("🍕", "pizza"),
    ("🌭", "hotdog"),
    ("🥪", "sandwich"),
    ("🌮", "taco"),
    ("🌯", "burrito"),
    ("🫔", "tamale"),
    ("🥗", "salad"),
    ("🍝", "spaghetti"),
    ("🍜", "ramen"),
    ("🍲", "stew"),
    ("🍛", "curry"),
    ("🍣", "sushi"),
    ("🍱", "bento"),
    ("🥟", "dumpling"),
    ("🍩", "donut"),
    ("🍪", "cookie"),
    ("🎂", "cake"),
    ("🍰", "shortcake"),
    ("🧁", "cupcake"),
    ("🍫", "chocolate"),
    ("🍬", "candy"),
    ("🍭", "lollipop"),
    ("🍮", "custard"),
    ("🍯", "honey"),
    ("☕", "coffee"),
    ("🍵", "tea"),
    ("🧃", "juice box"),
    ("🍺", "beer"),
    ("🍻", "cheers"),
    ("🥂", "champagne"),
    ("🍷", "wine"),
    ("🍸", "cocktail"),
    ("🍹", "tropical drink"),
    ("🧊", "ice"),
];

static TRAVEL: &[(&str, &str)] = &[
    ("🏠", "house"),
    ("🏡", "garden house"),
    ("🏢", "office"),
    ("🏥", "hospital"),
    ("🏦", "bank"),
    ("🏨", "hotel"),
    ("🏪", "store"),
    ("🏫", "school"),
    ("🏬", "department store"),
    ("🏛️", "classical"),
    ("⛪", "church"),
    ("🕌", "mosque"),
    ("🕍", "synagogue"),
    ("⛩️", "shinto"),
    ("🕋", "kaaba"),
    ("⛲", "fountain"),
    ("🏕️", "camping"),
    ("🏖️", "beach"),
    ("🏜️", "desert"),
    ("🏝️", "island"),
    ("🏔️", "mountain"),
    ("⛰️", "mountain2"),
    ("🌋", "volcano"),
    ("🗻", "fuji"),
    ("🗼", "tokyo tower"),
    ("🗽", "statue liberty"),
    ("✈️", "airplane"),
    ("🛩️", "small plane"),
    ("🚀", "rocket"),
    ("🛸", "ufo"),
    ("🚁", "helicopter"),
    ("🚂", "train"),
    ("🚗", "car"),
    ("🚕", "taxi"),
    ("🚌", "bus"),
    ("🚲", "bike"),
    ("🛵", "scooter"),
    ("🚤", "speedboat"),
    ("⛵", "sailboat"),
    ("🚢", "ship"),
    ("⚓", "anchor"),
    ("🗺️", "world map"),
    ("🧭", "compass"),
    ("🌍", "earth"),
    ("🌎", "earth americas"),
    ("🌏", "earth asia"),
    ("🌙", "moon"),
    ("⭐", "star"),
    ("🌟", "glowing star"),
    ("☀️", "sun"),
    ("🌤️", "partly sunny"),
    ("⛅", "cloudy"),
    ("🌧️", "rain"),
    ("⛈️", "storm"),
    ("🌈", "rainbow"),
    ("☔", "umbrella rain"),
    ("❄️", "snowflake"),
    ("⛄", "snowman"),
    ("🔥", "fire"),
    ("💧", "drop"),
    ("🌊", "wave"),
];

static OBJECTS: &[(&str, &str)] = &[
    ("⌚", "watch"),
    ("📱", "phone"),
    ("💻", "laptop"),
    ("⌨️", "keyboard"),
    ("🖥️", "desktop"),
    ("🖨️", "printer"),
    ("🖱️", "mouse"),
    ("💾", "floppy"),
    ("💿", "cd"),
    ("📷", "camera"),
    ("🎥", "movie camera"),
    ("📺", "tv"),
    ("📻", "radio"),
    ("🔔", "bell"),
    ("🔕", "no bell"),
    ("📢", "megaphone"),
    ("📣", "horn"),
    ("⏰", "alarm"),
    ("⏳", "hourglass"),
    ("🔋", "battery"),
    ("🔌", "plug"),
    ("💡", "bulb"),
    ("🔦", "flashlight"),
    ("🕯️", "candle"),
    ("🗑️", "trash"),
    ("🔑", "key"),
    ("🗝️", "old key"),
    ("🔒", "lock"),
    ("🔓", "unlock"),
    ("🔨", "hammer"),
    ("🪓", "axe"),
    ("⛏️", "pick"),
    ("🔧", "wrench"),
    ("🔩", "nut bolt"),
    ("⚙️", "gear"),
    ("📎", "paperclip"),
    ("✂️", "scissors"),
    ("📌", "pin"),
    ("📍", "round pin"),
    ("🖊️", "pen"),
    ("✏️", "pencil"),
    ("📝", "memo"),
    ("📁", "folder"),
    ("📂", "open folder"),
    ("📅", "calendar"),
    ("📊", "chart"),
    ("📈", "chart up"),
    ("📉", "chart down"),
    ("🗂️", "card index"),
    ("💰", "money bag"),
    ("💵", "dollar"),
    ("💴", "yen"),
    ("💶", "euro"),
    ("💷", "pound"),
    ("💎", "gem"),
    ("⚖️", "scales"),
    ("🧰", "toolbox"),
    ("🧲", "magnet"),
    ("🔗", "link"),
    ("📦", "package"),
    ("📫", "mailbox"),
    ("📬", "mailbox flag"),
    ("📧", "email"),
    ("📩", "envelope arrow"),
    ("🎁", "gift"),
    ("🎀", "ribbon"),
    ("🏷️", "label"),
    ("🔖", "bookmark"),
];

static SYMBOLS: &[(&str, &str)] = &[
    ("✅", "check"),
    ("❌", "cross"),
    ("❓", "question"),
    ("❗", "exclamation"),
    ("‼️", "double excl"),
    ("⭕", "circle"),
    ("🚫", "prohibited"),
    ("🔴", "red circle"),
    ("🟠", "orange circle"),
    ("🟡", "yellow circle"),
    ("🟢", "green circle"),
    ("🔵", "blue circle"),
    ("🟣", "purple circle"),
    ("⚫", "black circle"),
    ("⚪", "white circle"),
    ("🟥", "red square"),
    ("🟧", "orange square"),
    ("🟨", "yellow square"),
    ("🟩", "green square"),
    ("🟦", "blue square"),
    ("🟪", "purple square"),
    ("⬛", "black square"),
    ("⬜", "white square"),
    ("🔶", "orange diamond"),
    ("🔷", "blue diamond"),
    ("🔺", "red triangle"),
    ("🔻", "red triangle down"),
    ("💠", "diamond dot"),
    ("🔘", "radio button"),
    ("✨", "sparkles"),
    ("⚡", "zap"),
    ("💥", "boom"),
    ("🎵", "music"),
    ("🎶", "notes"),
    ("➡️", "right arrow"),
    ("⬅️", "left arrow"),
    ("⬆️", "up arrow"),
    ("⬇️", "down arrow"),
    ("↗️", "upper right"),
    ("↘️", "lower right"),
    ("↙️", "lower left"),
    ("↖️", "upper left"),
    ("🔀", "shuffle"),
    ("🔁", "repeat"),
    ("🔂", "repeat one"),
    ("▶️", "play"),
    ("⏸️", "pause"),
    ("⏹️", "stop"),
    ("⏺️", "record"),
    ("⏭️", "next track"),
    ("⏮️", "prev track"),
    ("🔊", "loud"),
    ("🔇", "mute"),
    ("🔔", "bell2"),
    ("📌", "pushpin"),
    ("♻️", "recycle"),
    ("🏁", "checkered flag"),
    ("🚩", "flag"),
    ("🏳️", "white flag"),
    ("🏴", "black flag"),
    ("⚠️", "warning"),
    ("🛑", "stop sign"),
    ("⛔", "no entry"),
    ("♾️", "infinity"),
    ("💯", "hundred"),
    ("🆗", "ok button"),
    ("🆕", "new"),
    ("🆓", "free"),
    ("ℹ️", "info"),
    ("🔤", "abc"),
    ("🔢", "numbers"),
    ("#️⃣", "hash"),
    ("*️⃣", "asterisk"),
    ("0️⃣", "zero"),
    ("1️⃣", "one"),
    ("2️⃣", "two"),
    ("3️⃣", "three"),
    ("©️", "copyright"),
    ("®️", "registered"),
    ("™️", "trademark"),
];

static FLAGS: &[(&str, &str)] = &[
    ("🇳🇴", "norway"),
    ("🇸🇪", "sweden"),
    ("🇩🇰", "denmark"),
    ("🇫🇮", "finland"),
    ("🇮🇸", "iceland"),
    ("🇬🇧", "uk"),
    ("🇺🇸", "usa"),
    ("🇨🇦", "canada"),
    ("🇦🇺", "australia"),
    ("🇳🇿", "new zealand"),
    ("🇩🇪", "germany"),
    ("🇫🇷", "france"),
    ("🇪🇸", "spain"),
    ("🇮🇹", "italy"),
    ("🇵🇹", "portugal"),
    ("🇳🇱", "netherlands"),
    ("🇧🇪", "belgium"),
    ("🇨🇭", "switzerland"),
    ("🇦🇹", "austria"),
    ("🇵🇱", "poland"),
    ("🇨🇿", "czech"),
    ("🇬🇷", "greece"),
    ("🇹🇷", "turkey"),
    ("🇷🇺", "russia"),
    ("🇺🇦", "ukraine"),
    ("🇯🇵", "japan"),
    ("🇰🇷", "south korea"),
    ("🇨🇳", "china"),
    ("🇮🇳", "india"),
    ("🇧🇷", "brazil"),
    ("🇲🇽", "mexico"),
    ("🇦🇷", "argentina"),
    ("🇿🇦", "south africa"),
    ("🇪🇬", "egypt"),
    ("🇮🇱", "israel"),
    ("🇸🇦", "saudi"),
    ("🇦🇪", "uae"),
    ("🇹🇭", "thailand"),
    ("🇻🇳", "vietnam"),
    ("🇮🇩", "indonesia"),
    ("🇵🇭", "philippines"),
    ("🇲🇾", "malaysia"),
    ("🇸🇬", "singapore"),
    ("🇭🇰", "hong kong"),
    ("🇹🇼", "taiwan"),
    ("🏳️‍🌈", "rainbow flag"),
    ("🏴‍☠️", "pirate flag"),
    ("🎌", "crossed flags"),
    ("🏁", "checkered"),
];

pub static EMOJI_CATEGORIES: &[EmojiCat] = &[
    EmojiCat { name: "Smileys", items: SMILEYS },
    EmojiCat { name: "People", items: PEOPLE },
    EmojiCat { name: "Animals", items: ANIMALS },
    EmojiCat { name: "Food", items: FOOD },
    EmojiCat { name: "Travel", items: TRAVEL },
    EmojiCat { name: "Objects", items: OBJECTS },
    EmojiCat { name: "Symbols", items: SYMBOLS },
    EmojiCat { name: "Flags", items: FLAGS },
];
